# ============================================================================
# 📦 KSR-SQL-Whitelist
# --------------------
# Ein Minecraft Paper/Spigot Plugin, das die Vanilla-Whitelist
# vollständig durch eine SQL-basierte Lösung ersetzt.
#
# Autor: Timy Liniger
# Website: https://ksrminecraft.ch/
# Version: 1.0-SNAPSHOT
# ============================================================================

name: KSR-SQL-Whitelist
version: '1.1'
main: ch.ksrminecraft.kSRSQLWhitelist.KSRSQLWhitelist
api-version: '1.21'
authors: [ "Timy Liniger" ]
description: SQL-backed whitelist management
website: https://ksrminecraft.ch/

# --------------------------------------------------------------------------
# ⚙️ PERMISSIONS
# --------------------------------------------------------------------------
# Die folgenden Permissions steuern den Zugriff auf die verschiedenen
# Whitelist-Befehle. Standardmäßig sind alle nur für Operatoren (op) erlaubt.
# --------------------------------------------------------------------------

permissions:

  # 🔑 Gesamte Rechtegruppe für das Plugin
  KSRSQLWhitelist.*:
    description: Grants access to all SQL-Whitelist actions
    children:
      KSRSQLWhitelist.add: true
      KSRSQLWhitelist.del: true
      KSRSQLWhitelist.on: true
      KSRSQLWhitelist.off: true

  # 🧩 Einzelberechtigungen
  KSRSQLWhitelist.add:
    description: Allows adding players to the whitelist
    default: op

  KSRSQLWhitelist.del:
    description: Allows removing players from the whitelist
    default: op

  KSRSQLWhitelist.on:
    description: Allows enabling the whitelist
    default: op

  KSRSQLWhitelist.off:
    description: Allows disabling the whitelist
    default: op

# --------------------------------------------------------------------------
# ⚙️ Commands
# --------------------------------------------------------------------------

commands:
  whitelist:
    description: SQL-Whitelist command interceptor (replaces vanilla /whitelist)
    usage: /whitelist <add|remove|on|off|list|reload>
    permission: minecraft.command.whitelist